[package]
name = "torush"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
ron = "0.8"
serde = { version = "1", features = ["derive"] }
